### ISSUE TITLE
Odd error output if no missing translations are found

### ISSUE THREAD

**Issue by pdehaan** [rbarbey/grunt-missing-i18n#5]
### Steps to reproduce:
1. Create a tasks/missing-i18n.js file and add the following bits:

``` javascript
module.exports = function (grunt) {
  'use strict';

  grunt.config('missingI18n', {
    strings: {
      filesSrc: ['app/**/*.js']
    }
  });
};
```
1. `$ grunt missingI18n`
### Expected results:

"You rule, dude!"
### Actual results:

```
Running "missingI18n:strings" (missingI18n) task
>> No missing translations in function logNumFiles(numFiles) {
>>     return numFiles + ' ' + grunt.util.pluralize(numFiles, 'file/files');
>>   }

Done, without errors.
```

**Comment by pdehaan** [comment]
If I use `files: ['app/**/*.{js,html,mustache}']` instead, I get the following error

> **Running tasks: missingI18n**
> 
> **Running "missingI18n" task**
> 
> **Running "missingI18n:strings" (missingI18n) task**
> _Verifying property missingI18n.strings exists in config...OK_
> _Warning: Cannot use 'in' operator to search for 'src' in app/*_/_.{js,html,mustache} Use --force to continue._
> 
> **Aborted due to warnings.**

**Comment by rbarbey** [comment]
Hey @pdehaan, thank you for contributing to this project! It's nice to see that it seems to be useful for more people than just myself.

**Comment by rbarbey** [comment]
Forgot to mention that I added a small how-to to the README file that illustrates how to use the plugin.
